yarnPath: .yarn/releases/yarn-4.3.1.cjs

# Have access to node_modules
# in the packages
#
# Plug'n'Play feature from yarn is still viable
# this just helps with autocompletion in the VSCode / whatever you're using
#
nodeLinker: node-modules